### ISSUE TITLE
Crash on Update dialog

### ISSUE THREAD

**Issue by softsan** [bitstadium/HockeySDK-Xamarin#133]
Hi,

Getting this error in our production env. when user get the hockey app update dialog and then it crashes.

```
android.view.WindowManager$BadTokenException: Unable to add window -- window android.view.ViewRootImpl$W@58f909 has already been added
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:970)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:381)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:100)
	at android.app.Dialog.show(Dialog.java:420)
	at net.hockeyapp.android.CrashManager.showDialog(CrashManager.java:637)
	at net.hockeyapp.android.CrashManager.access$100(CrashManager.java:49)
	at net.hockeyapp.android.CrashManager$2.onPostExecute(CrashManager.java:243)
	at net.hockeyapp.android.CrashManager$2.onPostExecute(CrashManager.java:216)
	at android.os.AsyncTask.finish(AsyncTask.java:695)
	at android.os.AsyncTask.-wrap1(Unknown Source:0)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by annakocheshkova** [comment]
Hi @softsan. Please make sure you pass Activity context, not application context when you register CrashManager: CrashManager.Register(this, "$Your_App_Id");

**Comment by annakocheshkova** [comment]
Hi @softsan, just a friendly ping, did you manage to resolve your issue?

**Comment by softsan** [comment]
Hi @annakocheshkova so in my code
 `HockeyApp.Android.CrashManager.Register(this, "MY_APP_ID");`
here `this` refers to the current class and i wrote above in my `MainActivity` so the context it will use it of MainActivity i think.

**Comment by dtrabo** [comment]
Hi @softsan, could you please provide detail steps to reproduce this? Where are you invoke Register methods?

**Comment by softsan** [comment]
@dtrabo - as i have mentioned in my previous comment i'm using it in MainActivity.
We have a xamarin.forms app and the `Register` is invoked from MainActivity.Create() and OnResume()

**Comment by Jamminroot** [comment]
Hello, @softsan, Im currently trying to reproduce your problem to be able to help, but I lack information on how to reproduce the problem on my side. 
Can you please give me info on the environment (IDE version, OS)?
Are you targeting only Android or is it both Andoid and iOS, and you only get error on Android?
How did you add hockeyapp to project? (e.g. nuget package for VS)
Can you leave hockeyapp-related code here, or, at least, give info on how and in which order you init the service on your app?
What are the steps I have to repeat to get similar error?
I really am willing to help, but unfortunately, It is unlikely without context of issue and details of the problem.

**Comment by MatkovIvan** [comment]
Hi, we haven't heard from you in a while so I'm closing this issue. Please reopen/comment if you have more info (that requested in the previous comment) for reproducing and investigation. Thanks.
