### ISSUE TITLE
Integrated update fails on Android 10

### ISSUE THREAD

**Issue by THplusplus** [bitstadium/HockeySDK-Xamarin#139]
We are currently rolling out an update to our previously released app version which still uses HockeyApp-Xamarin 5.1.0.

Users trying to install the update through the integrated update feature experience the following crash. Manual download and installation of the new app version works without issue.

Package: ….
Version Code: 19
Version Name: 1.2.0
Android: 10
Android Build: QP1A.190711.020
Manufacturer: Google
Model: Pixel 2
Thread: main-2
CrashReporter Key: ….
Start Date: 2019-09-19T10:32:53.003Z
Date: 2019-09-19T10:33:14.450Z
Format: Xamarin

android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.INSTALL_PACKAGE dat=file:///storage/emulated/0/Android/data/..../files/Download/4549e770-13f7-4462-8ead-5dbf7600c01d.apk typ=application/vnd.android.package-archive flg=0x10000000 }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2058)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1716)
	at android.app.Activity.startActivityForResult(Activity.java:5192)
	at android.app.Activity.startActivityForResult(Activity.java:5150)
	at android.app.Activity.startActivity(Activity.java:5521)
	at android.app.Activity.startActivity(Activity.java:5489)
	at net.hockeyapp.android.tasks.DownloadFileTask.onPostExecute(DownloadFileTask.java:206)
	at net.hockeyapp.android.tasks.DownloadFileTask.onPostExecute(DownloadFileTask.java:37)
	at android.os.AsyncTask.finish(AsyncTask.java:755)
	at android.os.AsyncTask.access$900(AsyncTask.java:192)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
Xamarin caused by: Java.Lang.RuntimeException: No Activity found to handle Intent { act=android.intent.action.INSTALL_PACKAGE dat=file:///storage/emulated/0/Android/data/..../files/Download/4549e770-13f7-4462-8ead-5dbf7600c01d.apk typ=application/vnd.android.package-archive flg=0x10000000 }
  --- End of managed Java.Lang.RuntimeException stack trace ---
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.INSTALL_PACKAGE dat=file:///storage/emulated/0/Android/data/de.cervis.partnerapp/files/Download/4549e770-13f7-4462-8ead-5dbf7600c01d.apk typ=application/vnd.android.package-archive flg=0x10000000 }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2058)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1716)
	at android.app.Activity.startActivityForResult(Activity.java:5192)
	at android.app.Activity.startActivityForResult(Activity.java:5150)
	at android.app.Activity.startActivity(Activity.java:5521)
	at android.app.Activity.startActivity(Activity.java:5489)
	at net.hockeyapp.android.tasks.DownloadFileTask.onPostExecute(DownloadFileTask.java:206)
	at net.hockeyapp.android.tasks.DownloadFileTask.onPostExecute(DownloadFileTask.java:37)
	at android.os.AsyncTask.finish(AsyncTask.java:755)
	at android.os.AsyncTask.access$900(AsyncTask.java:192)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by THplusplus** [comment]
This issue is already being discussed in the HockeySDK-Android repository: https://github.com/bitstadium/HockeySDK-Android/issues/432
